### PR TITLE
[Not merge] Let other threads work in RxQueryTest

### PR DESCRIPTION
**Pull request by nikitin-da**
Part of #826

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Just in case there is "Raw log" button on Travis, then just search for "Failed" :)

// Regular Travis log UI freezes my computer lol

capture

**Comment by nikitin-da** [comment]
Yes, I knew. It was very critical when log took 4Mb =)

**Comment by artem-zinnatullin** [comment]
Almost hour of reading source code (damn I love how we wrote StorIO, so readable), changes and debugging — facepalm.jpg

`parallelWritesWithoutTransaction` is incorrect :D 

`DefaultPutResolver` does put in transaction, which means that StorIO has all rights to merge notifications occurred during transaction, @nikitin-da your super useful logs (not joking) clearly show that StorIO delivers notifications, but less than test expect, also you can see that StorIO detects notification emission during transaction in the logs and simply merges them.

Haven't looked into second test that fails, but so far I'm thinking either about deleting `parallelWritesWithoutTransaction` test or renaming and fixing assertion.

I'll continue tonight and post separate PR with fixes, again, @nikitin-da thank you for great logs!

**Comment by geralt-encore** [comment]
this one can be closed, right?

**Comment by nikitin-da** [comment]
@geralt-encore sure! 
Fixed via #829

**Pull request closed without merging**
