### PR TITLE
StorIOSQLite Put Operation does not require RxJava in ClassPath

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Part of #144

@nikitin-da PTAL

### CODE REVIEW

**Comment by nikitin-da** [comment]
Excellent!

**Comment by artem-zinnatullin** [comment]
:shipit:

**Comment by artem-zinnatullin** [comment]
http://www.emoji-cheat-sheet.com

**Comment by nikitin-da** [comment]
it's punch :punch:
how do you thing what is it? :facepunch:

**Comment by artem-zinnatullin** [comment]
lol, stop it :smile:

**Comment by nikitin-da** [comment]
it's face punch!!!

**Pull request merged**
