### PR TITLE
Update Gradle 3.5 → 4.2.1.

### PR DESCRIPTION
**Pull request by artem-zinnatullin**

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Changelog https://github.com/gradle/gradle/releases

**Comment by artem-zinnatullin** [comment]
>Could not find or load main class org.gradle.wrapper.GradleWrapperMain

Hm, lemme see, I thought it was only my local problem because I used Linux subsystem on Windows

**Comment by nikitin-da** [comment]
the same problem on mac

**Comment by artem-zinnatullin** [comment]
Interesting, I've definitely used 4.2.1 at work, hmm. Either they've updated wrapper jar without new release and broke something or it's my Windows machine.

@nikitin-da can you please try to update on mac locally on master branch? `./gradlew wrapper --gradle-version 4.2.1`?

For now I'll update it to 4.2, works fine for me.

**Comment by artem-zinnatullin** [comment]
dafq

>Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

**Comment by nikitin-da** [comment]
After local update all works fine https://github.com/pushtorefresh/storio/commit/e63ee35e2cadf60c4cc3e9b3bbf3964917c0bd66

**Comment by artem-zinnatullin** [comment]
Yeah I think it's Windows uhhhhh, I'll update from my mac then, thanks man!

**Comment by artem-zinnatullin** [comment]
#826

**Pull request merged**
