### PR TITLE
Nexus-publish-plugin 0.1.1 and providing nexusPublishing params

### PR DESCRIPTION
**Pull request by nikitin-da**

### CODE REVIEW

**Comment by nikitin-da** [comment]
@artem-zinnatullin don't you know can we check case with publishing with varying IP addresses localy?

**Comment by nikitin-da** [comment]
The same error, we should find the way to check it locally

**Comment by artem-zinnatullin** [comment]
What's the error exactly?

**Comment by nikitin-da** [comment]
Error message is `WrongNumberOfRepositories was thrown with message 'Wrong number of received repositories in state 'open'. Expected 1, received 4'.`
https://travis-ci.org/pushtorefresh/storio/builds/473768167
https://github.com/Codearte/gradle-nexus-staging-plugin/issues/76#issuecomment-451615386

**Comment by nikitin-da** [comment]
uploadArchives is not supported(

**Pull request merged**
