### PR TITLE
Update readme according to Kotlin integration changes

### PR DESCRIPTION
**Pull request by geralt-encore**

### CODE REVIEW

**Comment by geralt-encore** [comment]
Let's merge it as soon as 2.0 goes live to avoid any possible confusion

**Comment by artem-zinnatullin** [comment]
2.0.0 is live :)

**Comment by geralt-encore** [comment]
Can't merge with failed CI :(

**Comment by artem-zinnatullin** [comment]
#824 should fix that, let's see!

**Comment by artem-zinnatullin** [comment]
>No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

Ok, I think this is separate issue that we have for a long time, either it's a deadlock somewhere in tests or Robolectric, or we consume too much resources

**Comment by artem-zinnatullin** [comment]
See #826

**Pull request merged**
