### PR TITLE
Remove unused @SuppressWarning

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
I'll merge after CI.

### CODE REVIEW

**Comment by nikitin-da** [comment]
It seems you broke everything with this PR!

**Comment by nikitin-da** [comment]
Shell I merge it?

**Comment by artem-zinnatullin** [comment]
Why not? And why you write `shell` instead of `shall`? :)

**Comment by nikitin-da** [comment]
It's just T9. I'll correct it=)

**Pull request merged**
