### PR TITLE
Type mapping now works for subclasses

### LINKED ISSUE #365: Type mapping with AutoValue/AutoParcel
Link to discussion on reddit: https://www.reddit.com/r/androiddev/comments/38nx2t/weekly_anything_goes_thread/crxm900

The problem:

`SQLiteTypeMapping` and `ContentResolverTypeMapping` store pairs for type mapping with exact class, for example: `[(Tweet.class, TweetPutResolver), (Tweet.class, TweetGetResolver)...]`.

But with `AutoValue` and `AutoParcel` it won't resolve required class.

> There was one hiccup with AutoParcel and SQLiteTypeMapping. AutoParcel generates child class for every annotated class, but it's package private and can't be used when creating type mapping but type mapping created using parent class doesn't work with child object since prepare operation uses getClass to find appropriate type mapping. For example:

```java
@AutoParcel
public abstract class Foo {
    abstract int id();
    abstract String bar();
    public static Foo create(int id, String bar) {
        return new AutoParcel_Foo(id, name);
}

StorIOSQLite storIOSQLite = new DefaultStorIOSQLite.Builder()
.sqliteOpenHelper(helper)
.addTypeMapping(Foo.class, new SQLiteTypeMapping.Builder<Foo>()
    .putResolver(new FooPutResolver())
    .getResolver(new FooGetResolver())
    .deleteResolver(new FooDeleteResolver())
    .build())
.build();

Foo foo = Foo.create(0, "baz"); // foo.getClass returns AutoValue_Foo

storIOSQLite
  .put()
  .object(foo)
  .prepare() // prepare can't find mapping for AutoValue_Foo
  .executeAsBlocking() 
```

> On user side it can be solved by specifying concrete right resolver for every operation or using generated class type in type mapping and resolver declaration neither of which very flexible. How it can be solved in library I have no idea. So for now I stopped using AutoValue for db entity objects (same with Gson based entities since AutoValue doesn't play nice with it either).

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Closes #365!

@nikitin-da PTAL, see #365 for description of implementation, I think that my implementation is pretty fast and "reflection" used only once, then it's cached.

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Don't merge until I'll add support for better inheritance processing.

**Comment by artem-zinnatullin** [comment]
@nikitin-da I've reimplemented typeMapping resolving, now it's faster and also support deep inheritance and complex relations like in your example with AutoValue, PTAL carefully at whole PR.

Also, I've added unit and integration tests for AutoValue/AutoParcel support.

**Comment by artem-zinnatullin** [comment]
BTW, it also closes #372!

**Comment by nikitin-da** [comment]
Awesome! Infinitely better autoValue support then Gson =)

**Comment by artem-zinnatullin** [comment]
Haha, yeah :)
9 июня 2015 г. 1:00 PM пользователь "Dmitrii Nikitin" <
notifications@github.com> написал:

**Pull request merged**
