### PR TITLE
PreparedPut for StorIOContentProvider with PreparedPutObject impl

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Plus little refactoring (sorry for that..)

@nikitin-da take a look, please

Part of #164 

I'll add unit tests for `PreparedPut` after finishing all `PreparedPut` variants

### CODE REVIEW

**Comment by nikitin-da** [comment]
Cool!!
Annotations from new line produce many changes=)

**Comment by artem-zinnatullin** [comment]
Yeah, I decided to use standard IDEA formatting rules :smile:

**Comment by nikitin-da** [comment]
Ivan is very angry about inline style;)

**Comment by artem-zinnatullin** [comment]
Haha :)

Actually, I don't love inline style non-determenistic, when line is too long, it will wrap annotation, if line is not very long, it won't..

**Pull request merged**
