### PR TITLE
Switch back to Android Gradle Plugin 1.3.1

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
…out localization for "@" symbol.

Trivial, I'll merge after CI.

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
@nikitin-da I can not reproduce this lint fail on Mac OS, can you please try to build this branch on your Linux machine? Looks like Android Gradle Plugin 1.4.0-beta6 has some problems with Lint on Linux.

**Comment by nikitin-da** [comment]
Sure, I'll try.

**Comment by artem-zinnatullin** [comment]
Thanks!

вс, 11 окт. 2015 г. в 18:29, Dmitrii Nikitin <notifications@github.com>:

> Sure, I'll try.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pushtorefresh/storio/pull/538#issuecomment-147211476>.
>
-- 

@artem_zin

**Comment by nikitin-da** [comment]
I suggest use beta2, because it seems lint doesn't know about following versions 1.4.0-beta3-6: 
"The SDK platform-tools version ((23 rc2)) is too old to check APIs compiled with API 23;"

**Comment by nikitin-da** [comment]
Should I squash?

**Comment by artem-zinnatullin** [comment]
@nikitin-da can you please try to update the SDK on your machine and try again with beta6? I am afraid, beta2 will stop working soon.

**Comment by artem-zinnatullin** [comment]
@nikitin-da PTAL :) I've switched back to 1.3.1, **** this shit

**Comment by nikitin-da** [comment]
Ook)

**Pull request merged**
