### PR TITLE
Compile checkable required params

### PR DESCRIPTION
**Pull request by nikitin-da**
@artem-zinnatullin PTAL
Mandatory builder for PreparedGetListOfObjects

### CODE REVIEW

**Comment by nikitin-da** [comment]
Part #218

**Comment by nikitin-da** [comment]
I did'n find another builders with that issue.
So there are only two places.

**Comment by artem-zinnatullin** [comment]
Just tried in IDE, it allows me to set only one of mandatory params and I can call `prepare()`

:(

**Comment by artem-zinnatullin** [comment]
Put Operation requires `MapFunc` and PutResolver

You can solve this issue via additional classes, it will also require
special order of methods calls.

For example: `withQuery().withMapFunc()`, when `withQuery()` returns
`non-compete` builder with availability to call `withMapFunc()`  and
`withMapFunc()` returns `CompleteBuilder`

I saw something similar in one of links that I noticed in the issue

пн, 6 апр. 2015, 10:00, Dmitrii Nikitin <notifications@github.com>:

**Comment by nikitin-da** [comment]
Damn, I was concentrated only on logical disjunction and forgot about another required fields.

**Comment by artem-zinnatullin** [comment]
:)

пн, 6 апр. 2015, 10:56, Dmitrii Nikitin <notifications@github.com>:

**Comment by nikitin-da** [comment]
Updated. Do we need be able to set `get resolver` at every step?

**Comment by artem-zinnatullin** [comment]
Great, works like charm!

Yes, I think user should be able to set `GetResolver` at every step, it's one of the benefits of the Builder pattern — order of calls does not matter (except required fields).

I am merging PR, but it does not closes #218 because there are builders for `Queries` and some of them have required fields

Good job :+1:

**Pull request merged**
