### PR TITLE
kotlin data classes support in annotation processor

### PR DESCRIPTION
**Pull request by pbochenski**
I've added support for kotlin data classes. 
Please see kotlin sample app for usage and discussion of different approaches.

### CODE REVIEW

**Comment by nikitin-da** [comment]
Hi, @pbochenski! 
Thank you for the work, but @geralt-encore has made this feature in #720 
The idea with sample application on kotlin is great! But will it be more united if it will be particular activity (package) in storio-sample-app? (To prevent multiple modules for each use case). 
And after @geralt-encore changes will be merged.
Thank you!

**Comment by pbochenski** [comment]
Ah, I didn't see his PR. I just saw open issue and started working on it. I guess I was too slow 😞 
I can work on kotlin activity in sample app after @geralt-encore pr is merged :)

**Comment by artem-zinnatullin** [comment]
@pbochenski damn, very sorry for that situation…

We've just merged #720, can you please check it with your Kotlin sample (only StorIOSQLite for now) and post a PR with sample app and changes required for it to work with changes made in #720? That would be very appreciated!

Thank you for contribution :)

**Comment by pbochenski** [comment]
About the sample app. I think that doing separate app for kotlin is good idea and the reason is that kapt is needed for annotation processing in kotlin. And storeIO probably needs java example for people to look at. 
What do you think?

**Comment by geralt-encore** [comment]
@pbochenski if you have any questions about implementation while doing sample app - just ask :)

**Comment by nikitin-da** [comment]
Can we discuss it in issue #622 )?

**Pull request closed without merging**
