### PR TITLE
Error message fix

### LINKED ISSUE #604: Put error message is wrong
Hi,

first, thank you for this awesome library! Its so simple and fun to use. :)

I've found a small but confusing typo. I'm getting the message "Error has occurred during Delete operation." after a failed PUT operation. You can find the code [here.](https://github.com/pushtorefresh/storio/blob/515f740a210c702b5bda170afcb07b4391b2f6e1/storio-sqlite/src/main/java/com/pushtorefresh/storio/sqlite/operations/put/PreparedPutContentValues.java#L58)

Thanks!

### PR DESCRIPTION
**Pull request by nikitin-da**
Closes #604 
@artem-zinnatullin PTAL

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
:+1:

**Comment by artem-zinnatullin** [comment]
You've checked all operations?…

**Comment by nikitin-da** [comment]
Yep!

**Comment by artem-zinnatullin** [comment]
Cool, thanks!

On Wed, 27 Jan 2016, 19:45 Dmitrii Nikitin <notifications@github.com> wrote:

> Yep!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pushtorefresh/storio/pull/605#issuecomment-175738300>.
>
-- 

@artem_zin

**Pull request merged**
