### PR TITLE
RxJava 1.0.15, supportLibs 23.1.0

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
@nikitin-da PTAL :)

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Lol, build tools 23.0.2 is not available on Travis… @nikitin-da do you see it on your Linux?

**Comment by nikitin-da** [comment]
Hm, nope. I can build it with 23.0.2

**Comment by artem-zinnatullin** [comment]
:(

**Comment by artem-zinnatullin** [comment]
Travis ucked up, build finished successfully, but status does not sent on GitHub :(

**Comment by nikitin-da** [comment]
Ok, I'll merge it

**Comment by artem-zinnatullin** [comment]
Let's wait… I've cleaned build caches and restarted the build

**Comment by artem-zinnatullin** [comment]
@nikitin-da also, master branch is protected by this checks, so you can not merge it :)

**Pull request merged**
