### PR TITLE
Builder with mandatory filds for PreparedPutObjects

### PR DESCRIPTION
**Pull request by nikitin-da**
@artem-zinnatullin Check please

Refs #218

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
LGTM

**Comment by nikitin-da** [comment]
о_О
https://github.com/square/lgtm

**Comment by artem-zinnatullin** [comment]
Wow, LGTM — Looks Good To Me

**Comment by artem-zinnatullin** [comment]
Thanks!

**Pull request merged**
