### PR TITLE
Rename ExecSql to ExecuteSQL

### LINKED ISSUE #338: Rename ExecSql Operation to ExecSQL for consistency
We use `SQL` instead of `Sql` in all `StorIOSQLite` codes, so it'll be great to have consistency here.

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Closes #338.

@nikitin-da PTAL

### CODE REVIEW

**Comment by nikitin-da** [comment]
retest this please

**Comment by artem-zinnatullin** [comment]
***ing emulator.

**Comment by nikitin-da** [comment]
Interesting

**Comment by artem-zinnatullin** [comment]
Loooool, I thought that my comment about emulator restarted the build :D

**Comment by nikitin-da** [comment]
hot key xD

**Pull request merged**
