### PR TITLE
Add integration of Travis CI with Codecov.io

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Similar to https://github.com/artem-zinnatullin/qualitymatters/pull/122

@nikitin-da, @karlicoss PTAL

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
I'd like to merge this before #601 and #629 and then rebase those PRs to see that we don't have code coverage regression cc @nikitin-da, @geralt-encore

**Comment by nikitin-da** [comment]
looks good :+1:

**Comment by nikitin-da** [comment]
but meta!)

**Comment by artem-zinnatullin** [comment]
Wtf, lint failed but build succeed…

**Comment by artem-zinnatullin** [comment]
Added required Android SDK dependencies, lint should pass now

**Pull request merged**
