### PR TITLE
Part1: Forward notifications between StorIOSQLite v1 and v3

### PR DESCRIPTION
**Pull request by nikitin-da**
Part of #875

### CODE REVIEW

**Comment by geralt-encore** [comment]
@nikitin-da @artem-zinnatullin Do you think that it is a good idea to have it? I mean a migration to a newer version shouldn't be hard and it is a lot of code to maintain and care about.

**Comment by nikitin-da** [comment]
@geralt-encore happy new year man! 🎄 🍾 🍊

**Comment by nikitin-da** [comment]
>a migration to a newer version shouldn't be hard

I'm totally agree that migration of storio itself is not a big deal and can be done by single pull request.
But most likely we have to migrate to RxJava2 as well and here we can meet some problems if we use storio-rx widely. 
My current project has no separate repository that can be fast converted to storio3 but keep outer interface on rx1 by RxJavaInterop. I guess I'm not alone in this problem and many projects will have to migrate storio and rx stepwise.

>it is a lot of code to maintain and care about

Firstly I thought that some gist with notifications sharing will be enough. But lately realized that I have to migrate changes and mapping as well. It is not feet to gist and requires tests..
What about code maintaining I think to prevent induced changes in this module we may use fixed storio 3.0.0 version [here](https://github.com/pushtorefresh/storio/pull/876/files#diff-4334bc0ffc5848f5d54b8d765ee2e552R20) instead of subproject dependency.
And than it will lead to separate interop version (because otherwise interop version will outrun storio itself). 

Or maybe we should create another repository and publish it independently like it do @akarnokd.
@artem-zinnatullin any thoughts?

**Comment by geralt-encore** [comment]
> @geralt-encore happy new year man! 🎄 🍾 🍊
Thanks, mate! Happy new year to you, too!

I see what problem you are trying to solve and it feels more like RxJava migration related than StorIO related. Also, it might get out of hand pretty fast. Imagine that we would release storio4 and 3 more migrations are needed. 

I like the idea of keeping it in separate repo and publishing as an independent artefact.

**Pull request closed without merging**
