### PR TITLE
Reduce build log level, thnx to Travis 10k limit

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Travis has limit: 10k logs per build, and we can not see our wanted result in the end:

```
BUILD SUCCESSFUL

Total time: 2 mins 26.981 secs```

So I removed `--info`, but now we can not see tests results…

Uh

### CODE REVIEW

**Comment by nikitin-da** [comment]
retest this please

**Comment by artem-zinnatullin** [comment]
@nikitin-da "retest this please" works only for Jenkins GitHub plugin, for Travis CI you need to relaunch build on their website, but I am not sure that button will be displayed for you (but it should).

**Comment by artem-zinnatullin** [comment]
I've restarted the build.

**Comment by nikitin-da** [comment]
`shouldReceiveChangeAfterEachDelete` again =(

**Pull request merged**
