### PR TITLE
Add mention to documentation that Query is a wrapper of query()

### PR DESCRIPTION
**Pull request by ArgirisKala**
I make this pull request for fixing #602 issue. Happy hacktoberfest :-)

### CODE REVIEW

**Comment by nikitin-da** [comment]
Hi @ArgirisKala ! Thank you for assistance! But I have doubts that @artem-zinnatullin means exactly this line, when hi filed issue ;)

**Comment by artem-zinnatullin** [comment]
yeah, I'd add it to the [Queries section](https://github.com/pushtorefresh/storio#queries) in the readme :)

**Comment by artem-zinnatullin** [comment]
yeah, I'd add it to the [Queries section](https://github.com/pushtorefresh/storio#queries) in the readme :)

**Comment by ArgirisKala** [comment]
ok, no problem

**Pull request closed without merging**
