### PR TITLE
Rename numberOfUpdatedRows to numberOfRowsUpdated

### LINKED ISSUE #177: Rename numberOfUpdatedRows to numberOfRowsUpdated
It's just more correct

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Prettifying API :)

Closes #177 

@nikitin-da check please

### CODE REVIEW

**Comment by nikitin-da** [comment]
Done

**Comment by artem-zinnatullin** [comment]
@nikitin-da wat?)

**Comment by nikitin-da** [comment]
Like your CTO, I spend less then 1 minute

**Comment by artem-zinnatullin** [comment]
Haha :+1: 

Fix typo: I spend less `than`

**Comment by nikitin-da** [comment]
gracias

**Pull request merged**
