### PR TITLE
Integration tests for StorIOContentResolver

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
@nikitin-da finally! 

Since most of integration tests for StorIOContentResolver can live normally in `storio-content-resolver/androidTest` I left them there, but I've moved "stream" tests to `storio-sample-app`, and rewrote them completely.

I decided to check only two emissions: initial and emission after some change (insert, update, delete), please take a look!

### CODE REVIEW

**Comment by public-ci-pushtorefresh** [comment]
Can one of the admins verify this patch?

**Comment by artem-zinnatullin** [comment]
Damn, Jenkins, what's wrong with you?

**Comment by artem-zinnatullin** [comment]
add to whitelist

**Comment by artem-zinnatullin** [comment]
test this please

**Comment by artem-zinnatullin** [comment]
ok to test

**Comment by artem-zinnatullin** [comment]
argh

**Comment by artem-zinnatullin** [comment]
Awesome, I've updated Jenkins plugins today and now it does not work with GitHub API, falling back to Travis CI.

**Comment by nikitin-da** [comment]
:+1: Cool!

**Pull request merged**
