### PR TITLE
Fix content resolver tests flakiness (READY FOR REVIEW)

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
In this PR I'll try to fix tests flakiness.

Unfortunately, I cannot reproduce errors that happen on Travis CI on my machines, so all work will be done as growing PR and then (hope it'll be successful) I'll squash this and it will be ready to merge into main branch.

Until I write that this PR is ready for review, you don't need to check it.

See #439.

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
3rd re-run of the build and I got one stacktrace:

```
com.pushtorefresh.storio.contentresolver.integration.ObserveChangesTest > shouldReceiveChangeAfterEachDelete FAILED
    java.lang.AssertionError: Expected value = Changes{affectedUris=[content://com.pushtorefresh.storio.content_resolver.test/tweets]} was not received, timeout = 15000ms, expectedValues.size = 9
        at com.pushtorefresh.storio.test.AbstractEmissionChecker.awaitNextExpectedValue(AbstractEmissionChecker.java:70)
        at com.pushtorefresh.storio.contentresolver.integration.ObserveChangesTest.shouldReceiveChangeAfterEachDelete(ObserveChangesTest.java:137)
```

**Comment by artem-zinnatullin** [comment]
Another stacktrace:

```
com.pushtorefresh.storio.contentresolver.integration.InsertTest > insertAndDeleteTwice FAILED
    java.lang.AssertionError: Expected value = null was not received, timeout = 60000ms, expectedValues.size = 0
        at com.pushtorefresh.storio.test.AbstractEmissionChecker.awaitNextExpectedValue(AbstractEmissionChecker.java:70)
        at com.pushtorefresh.storio.contentresolver.integration.IntegrationTest.deleteUser(IntegrationTest.java:189)
        at com.pushtorefresh.storio.contentresolver.integration.InsertTest.insertAndDeleteTwice(InsertTest.java:41)
```

**Comment by artem-zinnatullin** [comment]
Looks like https://github.com/pushtorefresh/storio/commit/4e855befedf7b298b409c700021ac8d3c3dfc788 finally fixes this, 5 builds passed on Travis CI.

@nikitin-da can you PTAL at this PR?

**Comment by artem-zinnatullin** [comment]
I don't think that this PR should be squashed, all commits are pretty independent and useful as separate entities in the history, so @nikitin-da if you'll think that PR looks good — merge it :)

**Comment by nikitin-da** [comment]
Great!

**Pull request merged**
