### PR TITLE
Release 1.9.0

### PR DESCRIPTION
**Pull request by nikitin-da**

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Oh nice! I remember that we had some issue/feature that was half-done and committed but not sure about it, don't you see anything like this? 

Just afraid that we can ship half-completed state of feature/issue.

**Comment by nikitin-da** [comment]
Hm, I don't see such PR's merged in master. Just #629 looks like by name, but put and delete operation is whole list of completable operations.

**Comment by artem-zinnatullin** [comment]
ok, 👍 from me, let's wait for review from @karlicoss and I'll publish it on maven central!

Btw, I'm totally ok with frequent releases, like each 1/2/3/4/whatever weeks, should be good for users and library.

// Many thanks to you guys, I'm sorry that I can't actively participate in library development at the moment.

**Comment by artem-zinnatullin** [comment]
@karlicoss any input?

**Comment by karlicoss** [comment]
@artem-zinnatullin @nikitin-da looks good, let's ship it!

**Pull request merged**
