### PR TITLE
Add missing semicolon in AutoValue example

### PR DESCRIPTION
**Pull request by mlegy**

### CODE REVIEW

**Comment by geralt-encore** [comment]
@nikitin-da is there something wrong with Travis?

**Comment by nikitin-da** [comment]
Yep, Travis decided this request is fishy =(
I mail to the Travis support and I hope we will merge this PR soon.

**Comment by nikitin-da** [comment]
@mlegy sorry for such delay=(
@MariadeAnton from Travis team ask you to log into https://travis-ci.org/. It seems you has not logged into Travis yet.
Hopefully this will give more visibility into issue why request is fishy.
Thank you in advance!

**Comment by artem-zinnatullin** [comment]
Thanks!

**Pull request merged**
